cursor #dbe3ed
cursor_text_color #bfc7d0

foreground            #dbe3ed
background            #0c141b
selection_foreground  #1d314c
selection_background  #b4c8e9
url_color             #88ceff

color0   #0c141b
color1   #e64c49
color2   #73d66e
color3   #dbcf7b
color4   #3d89be
color5   #77a1bf
color6   #88ceff
color7   #abb2bf
color8   #5c6370
color9   #e05f62
color10  #89e086
color11  #e8de97
color12  #91ddff
color13  #3d8399
color14  #5b7ca4
color15  #ffffff
