[mgr]

prepend_keymap = [
  { on = [
    "g",
    "s",
  ], run = "cd ~/Documents/School/Year-4/Sem-C", desc = "school sem c" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/UserWorkspace/KiCad/projects/Precision_Scope/docs", desc = "final project kicad" },
  { on = [
    "g",
    "b",
  ], run = "cd ~/Documents/Yovel/Books", desc = "books" },
]
