[colors]
background = '#0c141b'
foreground = '#dbe3ed'

cursor_bg = '#88ceff'
cursor_fg = '#0c141b'
cursor_border = '#88ceff'

selection_bg = '#004c6e'
selection_fg = '#dbe3ed'

ansi = ['#0c141b', '#e64c49', '#73d66e', '#dbcf7b', '#3d89be', '#77a1bf', '#88ceff', '#abb2bf']
brights = ['#5c6370', '#e05f62', '#89e086', '#e8de97', '#91ddff', '#3d8399', '#5b7ca4', '#ffffff']
