[colors.primary]
background = '#0c141b'
foreground = '#dbe3ed'

[colors.selection]
text = '#dbe3ed'
background = '#004c6e'

[colors.cursor]
text = '#0c141b'
cursor = '#88ceff'

[colors.normal]
black   = '#0c141b'
red     = '#e64c49'
green   = '#73d66e'
yellow  = '#dbcf7b'
blue    = '#3d89be'
magenta = '#77a1bf'
cyan    = '#88ceff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f62'
green   = '#89e086'
yellow  = '#e8de97'
blue    = '#91ddff'
magenta = '#3d8399'
cyan    = '#5b7ca4'
white   = '#ffffff'
